### ISSUE TITLE
No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by reinaldo-calderon-team** [ZacharyChang/kcui#1]
when run ./kcui I have this message:
No Auth Provider found for name "gcp" then app crash 

OS: Big Sur 20A5364e

**Comment by ZacharyChang** [comment]
Seems that you are using a cluster on GKE. I just found the auth plugin in client-go library is not loaded by default. 
I'll fix this soon.

**Comment by ZacharyChang** [comment]
You can find the fixed version [here](https://github.com/ZacharyChang/kcui/releases/tag/v0.1.3-alpha) @reinaldo-calderon-team 
If this happens again, please provide more information about the kubernetes cluster version and GKE version. I'll test on the target platform.

**Comment by reinaldo-calderon-team** [comment]
@ZacharyChang, it's working now, thank you.

best
